### ISSUE TITLE
Liquid Exception: Liquid syntax error on `make site`

### ISSUE THREAD

**Issue by kairstenfay** [swcarpentry/sql-novice-survey#299]
Hi fellow carpenters,

I've recently started contributing to this lesson. Unfortunately I'm unable to build the site locally. 

When I run `make site`, I get this output:
```
jekyll serve
Configuration file: /home/kairsten/carpentries/sql-novice-survey/_config.yml
            Source: /home/kairsten/carpentries/sql-novice-survey
       Destination: /home/kairsten/carpentries/sql-novice-survey/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 34): Unknown tag 'link' in _includes/navbar.html, included in _layouts/base.html
jekyll 3.1.6 | Error:  Liquid syntax error (line 34): Unknown tag 'link'
Makefile:26: recipe for target 'serve' failed
make: *** [serve] Error 1
```

I don't normally use `make` or `jekyll`, so this could be an issue on my end. 

Software:
operating system: Ubuntu
`make` version: GNU Make 4.1
`jekyll` version: 3.1.6

**Comment by henrykironde** [comment]
run `make serve`

**Comment by kairstenfay** [comment]
> run `make serve`

`make serve` results in the same error.

**Comment by fmichonneau** [comment]
Hi @kairstenfay :wave:

You're running an older version of Jekyll. We're in the process of rewriting our setup instructions for installing Jekyll. It's currently in a PR: https://github.com/carpentries/lesson-example/pull/276/files#diff-2cc0b07f42930e4520820be1fe66f913R275 but if you'd be willing to give it a try and give us some feedback it'd be greatly appreciated. Thanks!

**Comment by kairstenfay** [comment]
Hi @fmichonneau : 

I followed the steps in the PR you linked. Steps 1 and 2 under *Linux (Ubuntu)*, plus the two steps under *For Everyone*. My error has changed. Here is the output I see now:

```
$ make serve
jekyll serve
/var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
Configuration file: /home/kairsten/carpentries/sql-novice-survey/_config.yml
Configuration file: /home/kairsten/carpentries/sql-novice-survey/_config.yml
Configuration file: /home/kairsten/carpentries/sql-novice-survey/_config.yml
            Source: /home/kairsten/carpentries/sql-novice-survey
       Destination: /home/kairsten/carpentries/sql-novice-survey/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/usr/lib/ruby/vendor_ruby/kramdown/version.rb:13: warning: already initialized constant Kramdown::VERSION
/var/lib/gems/2.5.0/gems/kramdown-1.17.0/lib/kramdown/version.rb:13: warning: previous definition of VERSION was here
/usr/lib/ruby/vendor_ruby/kramdown/element.rb:507: warning: already initialized constant Kramdown::Element::CATEGORY
/var/lib/gems/2.5.0/gems/kramdown-1.17.0/lib/kramdown/element.rb:507: warning: previous definition of CATEGORY was here
/usr/lib/ruby/vendor_ruby/kramdown/options.rb:36: warning: already initialized constant Kramdown::Options::Definition
/var/lib/gems/2.5.0/gems/kramdown-1.17.0/lib/kramdown/options.rb:36: warning: previous definition of Definition was here
/usr/lib/ruby/vendor_ruby/kramdown/options.rb:39: warning: already initialized constant Kramdown::Options::ALLOWED_TYPES
/var/lib/gems/2.5.0/gems/kramdown-1.17.0/lib/kramdown/options.rb:39: warning: previous definition of ALLOWED_TYPES was here
  Liquid Exception: undefined method `includes_load_paths' for #<Jekyll::Site:0x000055cee71d5b80> in _layouts/episode.html
jekyll 3.1.6 | Error:  undefined method `includes_load_paths' for #<Jekyll::Site:0x000055cee71d5b80>
Makefile:26: recipe for target 'serve' failed
make: *** [serve] Error 1
```

**Comment by henrykironde** [comment]
Could you try these steps.

`apt-get remove jekyll` (repeate till no older versions exist, I would also try  `sudo apt-get remove jekyll `to make sure jekyll is removed )
`gem uninstall jekyll`
`gem install jekyll bundler`

check the paths too if they are set according to https://jekyllrb.com/docs/installation/ubuntu/
```j
echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
```

**Comment by kairstenfay** [comment]
Thanks @henrykironde. 

I purged both ruby and jekyll from my system and reinstalled. I followed the jekyll installation steps from the website you linked (https://jekyllrb.com/docs/installation/ubuntu/). I verified I am able to create and serve a newly generated jekyll website. 

I re-ran `bundle update` and then `make serve` in `sql-novice-survey`. I am getting a different error now when I run `make serve`:

```
jekyll serve
Traceback (most recent call last):
        10: from /home/kairsten/gems/bin/jekyll:23:in `<main>'
         9: from /home/kairsten/gems/bin/jekyll:23:in `load'
         8: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
         7: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
         6: from /home/kairsten/.gem/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
         5: from /home/kairsten/.gem/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:26:in `setup'
         4: from /home/kairsten/.gem/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:26:in `map'
         3: from /home/kairsten/.gem/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:148:in `each'
         2: from /home/kairsten/.gem/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:148:in `each'
         1: from /home/kairsten/.gem/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:31:in `block in setup'
/home/kairsten/.gem/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated i18n 1.7.0, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
Makefile:26: recipe for target 'serve' failed
make: *** [serve] Error 1
```

When I prepend with `bundle exec` as recommended in the Error message, I get: 
```
$ bundle exec make serve
jekyll serve
Configuration file: /home/kairsten/carpentries/sql-novice-survey/_config.yml
            Source: /home/kairsten/carpentries/sql-novice-survey
       Destination: /home/kairsten/carpentries/sql-novice-survey/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  Liquid Exception: "<USERNAME>/<PROJECT>" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys. in /home/kairsten/carpentries/sql-novice-survey/_episodes/01-select.md
jekyll 3.8.5 | Error:  "<USERNAME>/<PROJECT>" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys.
Makefile:26: recipe for target 'serve' failed
make: *** [serve] Error 1
```

**Comment by henrykironde** [comment]
@kairstenfay could you try one last thing. Clone the a fresh repo and try again in a different location

**Comment by fmichonneau** [comment]
@kairstenfay thanks for reporting this. I've looked a little more into it, and it boils down to the fact that the lesson uses the `site.github.url`. I provide a little more context in the PR #303. 

In the meantime, I think that if you remove the Gemfile and the Gemfile.lock from the root of the lesson folder, you should be able to run `jekyll serve` and to render the lesson.

**Comment by henrykironde** [comment]
Thanks @kairstenfay. I think this solves the issue. Feel free to open if the current master is not working as expected.
